SELECT A.FOOD_TYPE
    , A.REST_ID
    , A.REST_NAME
    , A.FAVORITES
FROM REST_INFO AS A
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FA FROM REST_INFO GROUP BY FOOD_TYPE) AS B
ON A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.MAX_FA
ORDER BY A.FOOD_TYPE DESC
